### PR TITLE
Implement AccBBS + fix max mode

### LINKED ISSUE #297: Accelerated BBS Play
Need to implement AcceleratedBBSPlay.

from @Braindead on discord:

```
the formula is 
Acc BBS:
   500,000*GR+25,000 for a 1 planet PRT (acc BBS)
   (500,000GR+25,000).8 for the HW for a 2-lanet PRT (IT and PP)
   (500,000GR+25,000).4 for the 2nd planet for a 2-lanet PRT (IT and PP)

Non Acc BBS:
   25,000 for a 1-planet PRT
   20,000 for the HW for a 2-planet PRT
   10,000 for the 2nd planet for a 2-planet PRT
```

### LINKED ISSUE #580: Incorrect scanner range on JoaT ship designs in Max start mode
Prob need to compute design specs again afterwards
image

### PR DESCRIPTION
**Pull request by Bertie690**
Adds Accelerated BBS as well as fixing a small bug with start modes and doing some assorted code refactors.
Fixes #580 
Fixes #297 
image

### CODE REVIEW

File: cs/universegenerator.go [hunk 1]
```diff
@@ -40,17 +41,16 @@ func (ug *universeGenerator) Area() Vector {
...
 
-	for _, player := range ug.players {
+	for _, player := range ug.Players {
 		player.Race.Spec = computeRaceSpec(&player.Race, &ug.Rules)
-		player.discoverer = newDiscovererWithAllies(ug.log, player, ug.players)
+		player.discoverer = newDiscovererWithAllies(ug.log, player, ug.Players)
 	}
 
-	ug.universe = NewUniverse(ug.log, &ug.Rules)
+	u := NewUniverse(ug.log, &ug.Rules); ug.Universe = &u
```
Comment (sirgwain) [inline cs/universegenerator.go]: this should be two lines

File: cs/rules.go [hunk 2]
```diff
@@ -72,24 +72,29 @@ type Rules struct {
...
+	MinExtraPlanetMineralConcentration        int                                          `json:"minExtraPlanetMineralConcentration,omitempty"`
+	MinExtraWorldDistance                     int                                          `json:"minExtraWorldDistance,omitempty"`
+	MinHab                                    int                                          `json:"minHab,omitempty"`
+	MinHomeworldMineralConcentration          int                                          `json:"minHomeworldMineralConcentration,omitempty"`
+	MinMineralConcentration                   int                                          `json:"minMineralConcentration,omitempty"`
+	MinStartingMineralConcentration           int                                          `json:"minStartingMineralConcentration,omitempty"`
+	MinStartingMineralSurface                 int                                          `json:"minStartingMineralSurface,omitempty"`
+	RaceLeftoverPointsPerItem                 map[SpendLeftoverPointsOn]LeftoverPointsItem `json:"raceLeftoverPointsPerItem,omitempty"`
```
Comment (sirgwain) [inline cs/rules.go]: We can change this field type. It will break loads from old games. You can rename it and it will work, but if it has the same name it has to have the same type.

**Review by sirgwain — CHANGES_REQUESTED** [review]

File: cs/rules.go (hunk 2 above)
Comment (Bertie690) [reply cs/rules.go]: Ok reverted the change on local - just going to push to remote after test finishes

**Review by sirgwain — CHANGES_REQUESTED** [review]
I tried a new test game and got a divide by zero:

```
 panic: runtime error: integer divide by zero

 -> github.com/sirgwain/craig-stars/cs.(*universeGenerator).assignRaceStartingPointBonuses
/craig-stars/cs/universegenerator.go:473
```

File: db/upgrade.go [hunk 3]
```diff
@@ -51,38 +51,41 @@ func (tx *client) ensureUpgrade() error {
...
+		return nil
+	}
+
+	u := upgrade{tx: tx}
+	for current := version.Current; current < LATEST_VERSION; current++ {
+		log.Info().Msgf("upgrading database data from v%d to v%d", current, current+1)
+		// check each version and call the upgrade functionality
+		switch current {
+		case 0:
+			u.initStarterDB()
```
Comment (sirgwain) [inline db/upgrade.go]: we want to capture this error, we shouldn't ignore it.

File: magefiles/launch.go [hunk 4]
```diff
@@ -212,7 +212,6 @@ func Launch() error {
 
 // Launch the backend go server using air.
 func Launch_Backend() error {
-	mg.Deps(Generate)
```
Comment (sirgwain) [inline magefiles/launch.go:238]: we want this generate. Every time you change the server and rebuild it (with air) it should run generate.

File: db/upgrade.go (hunk 3 above)
Comment (Bertie690) [reply db/upgrade.go]: To be fair, the error was quite literally being overwritten in the literal next line anyways lol.
will add it shortly in any case

File: magefiles/launch.go (hunk 4 above)
Comment (Bertie690) [reply magefiles/launch.go:238]: Air runs `mage build-backend` to build the binary/server.
This is merely the command to boot air up, for which we hardly need to re-generate WASM serializers each time.
Probably a good idea to add a comment about that come to think about it...

**Review by sirgwain — DISMISSED** [review]

File: frontend/src/lib/types/Mineral.ts [hunk 5]
```diff
@@ -9,7 +9,7 @@ export const MineralTypes = {
 export const totalMinerals = (c: Mineral | undefined) =>
 	c ? (c.ironium ?? 0) + (c.boranium ?? 0) + (c.germanium ?? 0) : 0;
 
-export const addInt = (m: Mineral, i: number): Mineral => ({
+export const AddToAll = (m: Mineral, i: number): Mineral => ({
```
Comment (sirgwain) [inline frontend/src/lib/types/Mineral.ts]: JavaScript casing should be camelCase

**Review by sirgwain — CHANGES_REQUESTED** [review]

**Review by sirgwain — DISMISSED** [review]

**Review by sirgwain — APPROVED** [review]
