### PR TITLE
Starbase Cost revamps

### LINKED ISSUE #279: Costcalculation of Starbases is wrong
Starbases have to be much cheaper.

### PR DESCRIPTION
**Pull request by Bertie690**
The code is a bit complex, but it basically withdraws from a global tally to reduce the new item's price down to an initial floor (30% original), before applying an additional category-specific discount to reduce the price  even further (down to a minimum of 20% original).
Also fixed several bugs like incorrect miniaturization rounding & space dock not repairing enough

Fixes #279, #258, #226, #50

TODO:
- [x] Add ISB discount to functions `StarbaseUpgradeCost()` & `ShipDesignCost()`
- [x] Add tests for ISB discount in `StarbaseUpgradeCost()`
- [x] Add tests for `ShipDesignCost()` function
     - Only really need 4-5 tests: 2 for checking ship/starbase costs, 1 for ISB & the rest for error handling in event of invalid hulls/parts 
- [x] Add error checking to `producer.go` & `shipdesign.go`

### CODE REVIEW

File: ai/producer.go [hunk 1]
```diff
@@ -325,23 +325,22 @@ func (ai *aiPlayer) getYearsToBuildStarbase(planet *cs.Planet, design *cs.ShipDe
...
+		cost, err = costCalculator.StarbaseUpgradeCost(&ai.game.Rules, ai.Player.TechLevels, ai.Player.Race.Spec, existingStarbase, design)
 	} else {
-		cost, err = costCalculator.CostOfOne(ai.Player, item)
-		if err != nil {
-			return math.MaxInt, fmt.Errorf("calculate starbase cost %w", err)
-		}
+		cost = design.Spec.Cost
 	}
+	if err != nil {
+		return math.MaxInt, fmt.Errorf("calculate starbase cost %w", err)
```
Comment (sirgwain) [inline ai/producer.go:340]: if you have an err, you return 0, nil, or whatever the default value is for a type. It's expected the caller will not use that value because an error occurred.

File: cs/battleweapon.go [hunk 2]
```diff
@@ -44,7 +44,7 @@ type battleWeaponSlot struct {
 	accuracy float64
 
 	// the accuracy bonus to the torpedo
-	torpedoBonus float64
+	TorpedoBonus float64
```
Comment (sirgwain) [inline cs/battleweapon.go]: I'm not sure why this was changed to be an exported field? can you revert this please?

File: cs/bomb.go [hunk 3]
```diff
@@ -328,7 +328,7 @@ func (b *bomb) retroBombPlanet(planet *Planet, defender *Player, attacker *Playe
 	}
 }
 
-// getUnterraformAmount gets the amount we should unterraform with retro bombs
+// Get the amount we should unterraform with retro bombs
```
Comment (sirgwain) [inline cs/bomb.go]: It's not a hard and fast rule, but go convention is to start a comment with the function name. You can see that in the examples here: https://tip.golang.org/doc/comment

I have mixed feelings on this, which is why I don't apply it everywhere (also I'm just inconsistent)

File: db/schema/games/0001_schema.up.sql [hunk 4]
```diff
@@ -392,7 +392,7 @@ CREATE TABLE IF NOT EXISTS techEngines (
   canStealPlanetCargo NUMERIC,
   armor INTEGER,
   shield INTEGER,
-  torpedoBonus REAL,
+  TorpedoBonus REAL,
```
Comment (sirgwain) [inline db/schema/games/0001_schema.up.sql]: definitely revert changes to the schema.

File: cs/techstore.go [hunk 5]
```diff
@@ -1436,24 +1436,24 @@ var UltraStealthCloak = TechHullComponent{Tech: NewTech("Ultra-Stealth Cloak", N
...
 }
 var BattleSuperComputer = TechHullComponent{Tech: NewTech("Battle Super Computer", NewCost(0, 0, 25, 14), TechRequirements{TechLevel: TechLevel{Energy: 5, Electronics: 11}}, 50, TechCategoryElectrical),
 
-	Mass:            1,
-	InitiativeBonus: 2,
-	TorpedoBonus:    .3,
-	HullSlotType:    HullSlotTypeElectrical,
+	Mass:                   1,
+	InitiativeBonus:        2,
+	TorpedoBonus:           .7,
```
Comment (sirgwain) [inline cs/techstore.go]: this needs to be reverted. The bonus is 30%

File: cs/techstore.go [hunk 6]
```diff
@@ -1436,24 +1436,24 @@ var UltraStealthCloak = TechHullComponent{Tech: NewTech("Ultra-Stealth Cloak", N
 }
 var BattleComputer = TechHullComponent{Tech: NewTech("Battle Computer", NewCost(0, 0, 15, 6), TechRequirements{TechLevel: TechLevel{}}, 40, TechCategoryElectrical),
 
-	Mass:            1,
-	InitiativeBonus: 1,
-	TorpedoBonus:    .2,
-	HullSlotType:    HullSlotTypeElectrical,
+	Mass:                   1,
+	InitiativeBonus:        1,
+	TorpedoBonus:           .8,
```
Comment (sirgwain) [inline cs/techstore.go]: This needs to be reverted. The bonus is 20%

File: cs/tech.go [hunk 7]
```diff
@@ -100,7 +101,7 @@ type TechHullComponent struct {
 	CanStealPlanetCargo       bool          `json:"canStealPlanetCargo,omitempty"`
 	Armor                     int           `json:"armor,omitempty"`
 	Shield                    int           `json:"shield,omitempty"`
-	TorpedoBonus              float64       `json:"torpedoBonus,omitempty"`
+	TorpedoBonus              float64       `json:"torpedoInaccuracyMulti,omitempty"`
```
Comment (sirgwain) [inline cs/tech.go]: this needs to be reverted

File: cs/math.go [hunk 8]
```diff
@@ -13,10 +13,16 @@ func roundToNearest100(value int) int {
...
+	ratio := math.Pow(10, float64(precision))
+	return math.Round(val*ratio) / ratio
 }
 
+func roundHalfDown(x float64) float64 {
+	if x > 0 {
+		return math.Floor(x + 0.5)
+	}
+	return math.Ceil(x - 0.5)
+}
```
Comment (sirgwain) [inline cs/math.go:26]: Can you add a couple tests for this function? I'm not sure what its purpose is.

**Review by sirgwain — CHANGES_REQUESTED** [review]

File: ai/producer.go (hunk 1 above)
Comment (Bertie690) [reply ai/producer.go:340]: Yeah I should probably change this to reference `GetDesignCost()` directly (rather than calling it indirectly) since I can process the error as well.
Also for the record this is returning MaxInt as it's supposed to return the time needed to build something (and if an error occurs it will never get built anyways)

File: cs/battleweapon.go (hunk 2 above)
Comment (Bertie690) [reply cs/battleweapon.go]: oopsie - might be a leftover from an accidental find and replace some time ago

File: cs/math.go (hunk 8 above)
Comment (Bertie690) [reply cs/math.go:26]: it’s basically just math.Round() but we round halves down instead of away from 0.
Will make tests at home bc vscode web version can’t use extensions

File: cs/bomb.go (hunk 3 above)
Comment (Bertie690) [reply cs/bomb.go]: okee will undo later

File: cs/battletoken.go [hunk 9]
```diff
@@ -84,7 +84,7 @@ func newBattleToken(num int, position BattleVector, cargoMass int, token *ShipTo
 		maxRange := 0
 		for _, slot := range token.design.Spec.WeaponSlots {
 			weapon := techFinder.GetHullComponent(slot.HullComponent)
-			bws := newBattleWeaponSlot(&battleToken, slot, weapon, hull.RangeBonus, token.design.Spec.TorpedoBonus, token.design.Spec.BeamBonus)
+			bws := newBattleWeaponSlot(&battleToken, slot, weapon, hull.RangeBonus, token.design.Spec.torpedoBonus, token.design.Spec.BeamBonus)
```
Comment (sirgwain) [inline cs/battletoken.go]: heh, this one should be Capitalized because it's an exported field used by the UI and possibly the AI.

File: cs/production.go [hunk 10]
```diff
@@ -173,22 +175,46 @@ type builtShip struct {
...
 	for itemIndex := range planet.ProductionQueue {
 		item := planet.ProductionQueue[itemIndex]
 		maxBuildable := planet.maxBuildable(p.player, item.Type)
+		var err error
 		var cost Cost
 		if item.Type == QueueItemTypeStarbase && planet.Spec.HasStarbase {
-			cost = costCalculator.StarbaseUpgradeCost(planet.Starbase.Tokens[0].design, item.design)
+			cost, err = costCalculator.StarbaseUpgradeCost(p.rules, p.player.TechLevels, p.player.Race.Spec, planet.Starbase.Tokens[0].design, item.design)
+			if err != nil {
+				log.Warn().
```
Comment (sirgwain) [inline cs/production.go]: these errors should be returned. producer will need to be updated to return an error. I'm actually surprised it doesn't already since it looks up designs. I'm probably missing a check somewhere. :)

File: cs/shipdesign.go [hunk 11]
```diff
@@ -278,6 +281,16 @@ func ComputeShipDesignSpec(rules *Rules, techLevels TechLevel, raceSpec RaceSpec
 		InnateScanRangePenFactor: hull.InnateScanRangePenFactor,
 	}
 
+	var err error
+	spec.Cost, err = c.GetDesignCost(rules, techLevels, raceSpec, design)
+	if err != nil {
+		log.Warn().
```
Comment (sirgwain) [inline cs/shipdesign.go]: ComputeShipDesignSpec should be updated to return an error instead of logging a warning.

File: cs/tech.go [hunk 12]
```diff
@@ -415,13 +418,16 @@ func (t *Tech) GetPlayerCost(techLevels TechLevel, spec MiniaturizationSpec, cos
 		cost = cost.MultiplyFloat64(1 + costOffset.Bomb)
 	case TechCategoryTorpedo:
 		cost = cost.MultiplyFloat64(1 + costOffset.Torpedo)
+		//case TechCategoryOrbital && {some way to check if item is gate}
+		//	cost = cost.MultiplyFloat64(1 + costOffset.Stargate)
```
Comment (sirgwain) [inline cs/tech.go]: was this left in by mistake?

File: cs/math.go (hunk 8 above)
Comment (sirgwain) [reply cs/math.go:26]: Are we using this in a scenario where we need -.5 to round to 0?

**Review by sirgwain — CHANGES_REQUESTED** [review]

File: cs/tech.go (hunk 12 above)
Comment (Bertie690) [reply cs/tech.go]: Nah - I just wanted to put a comment there to remind myself to fix thing once the tag system gets implemented. 
Probably needs a big orange "TODO" marker come to think about it...

File: cs/math.go (hunk 8 above)
Comment (Bertie690) [reply cs/math.go:26]: Exactly - the easiest example I can think of is a max con B-17 bomber. 25% of 150 resources works out to be 37.5, which rounds DOWN to 37 resources.

File: cs/battletoken.go (hunk 9 above)
Comment (Bertie690) [reply cs/battletoken.go]: I realize that now - it borking tests.

**Review by sirgwain — APPROVED** [review]
