### PR TITLE
Fix WM move bonus error

### LINKED ISSUE #537: WM Move Bonus doesn't work
image
Not only does it not appear in the spec, it appears WM ships don't get their free move bonus in combat either. 
Were it the case, my DD would have 8 movement and travel 2 tiles every round, but it didn't.
(also now it makes sense why my scout catchers can't even catch a 4 move minicol...)

### PR DESCRIPTION
**Pull request by Bertie690**
Also temp fix to stop AI freighters from having armor while I work on tech tag stuff

Fixes #537

### CODE REVIEW

File: cs/shipdesign.go [hunk 1]
```diff
@@ -817,7 +823,10 @@ func DesignShip(techStore *TechStore, hull *TechHull, name string, player *Playe
 					break
 				}
 			}
-			// spare orbital slots left; use electrical items instead
+			// spare orbital slots left; use electrical items instead if possible
+			if hullSlot.Type&HullSlotTypeElectrical == 0 {
+				break
```
Comment (sirgwain) [inline cs/shipdesign.go:828]: Break will break out of the switch and ignore the component. I think you want to remove the if and let it fall through?

Comment (Bertie690) [reply cs/shipdesign.go:828]: No - this prevents it from putting computers in orbital only slots (since those fallthrough into the case for orbital/electrical)

Comment (sirgwain) [reply cs/shipdesign.go:828]: oh I see. I think I need to rearrange the order of those slots. That fall through shouldn't be possible and shouldn't require a break to fix, heh. Thanks!

**Review by sirgwain — APPROVED** [review]
