### PR TITLE
Fixed Genesis Device resetting production queue

### LINKED ISSUE #534: Genesis device resets planet build queue

### PR DESCRIPTION
**Pull request by Bertie690**
Fixes #534

### CODE REVIEW

File: cs/planet.go [hunk 1]
```diff
@@ -208,48 +213,55 @@ func (p *Planet) PopulateProductionQueueEstimates(rules *Rules, player *Player)
...
 func (p *Planet) emptyPlanet() {
 	p.PlayerNum = Unowned
 	p.Starbase = nil
+	// defenses & scanner disappear, other structures stay though
 	p.Scanner = false
-	p.Defenses = 0                  // defenses are all gone, rest of the structures can stay
-	p.PlanetOrders = PlanetOrders{} // clear any orders from previous owner
+	// clear any production or other orders from the previous owner
+	p.Defenses = 0                              
+	p.ProductionQueue = []ProductionQueueItem{}
```
Comment (sirgwain) [inline cs/planet.go]: The ProductionQueue is part of PlanetOrders.

File: cs/planet.go [hunk 2]
```diff
@@ -208,48 +213,55 @@ func (p *Planet) PopulateProductionQueueEstimates(rules *Rules, player *Player)
...
+		randomG = rules.random.Intn(rules.HabDropoffRange.Grav+1)
+	}
+	if rules.HabDropoffRange.Temp > 0 {
+		randomT = rules.random.Intn(rules.HabDropoffRange.Temp+1)
 	}
+	if rules.HabDropoffRange.Rad > 0 {
+		randomR = rules.random.Intn(rules.HabDropoffRange.Rad+1)
+	}
+
+	p.Hab = p.Hab.Add(Hab{randomG, randomT, randomR})
```
Comment (sirgwain) [inline cs/planet.go:257]: This is way harder to reason about than what it was before. What's the purpose in adding all this complexity? The code before is true to the original as far as I know.

**Review by sirgwain — CHANGES_REQUESTED** [review]

File: cs/planet.go (hunk 1 above)
Comment (Bertie690) [reply cs/planet.go]: oop

File: cs/planet.go (hunk 2 above)
Comment (Bertie690) [reply cs/planet.go:257]: making it customizable i guess idk
if you want me to revert it or smthng lmk

Comment (Bertie690) [reply cs/planet.go:257]: The main purpose is allowing the hab generation dropoff to be configurable in the `Rules` struct (as well as making it obey the existing `MaxHab` & `MinHab` rules variables rather than flat out ignoring them).
I just split up the like `1+rand.Intn(90)` and `+rand.Intn(10)` parts into 2 successive steps to avoid calling `rand.Intn(0)` and causing runtime panics.
TL;DR this makes hab bell curve configurable

**Review by sirgwain — APPROVED** [review]
