### PR TITLE
Fixed AR res and remote mining stuff

### LINKED ISSUE #176: to much ress on red worlds
image

### LINKED ISSUE #605: AR does not consider hab in resource formula
https://github.com/sirgwain/craig-stars/blob/4a39d02262689b9650e3cb8bc6e99a01876e8e93/cs/planet.go#L483

### PR DESCRIPTION
**Pull request by Bertie690**
Also refactored everything this side of the pacific bc I wanted to
Fixes #605

### CODE REVIEW

File: cs/planet.go [hunk 1]
```diff
@@ -146,23 +146,26 @@ func (p *Planet) population() int {
...
 
-// get the population that is productive. This takes into account overcrowding
-// anything over 3x is unproductive
-func (p *Planet) productivePopulation(pop, maxPop int) int {
-	return Min(pop, 3*maxPop)
+// get the amount population that is productive for producing resources.
+// This takes into account overcrowding
+func productivePopulation(pop, maxPop int, overcrowdPenalty, overcrowdResourceMax float64) int {
+	popOverCap := float64(pop) + Max(0, float64(pop-maxPop)*overcrowdPenalty)
+	// TODO: Add fancy rounding later
```
Comment (sirgwain) [inline cs/planet.go]: what fancy rounding? Can you raise an issue for it rather than add a todo?

File: cs/planet.go [hunk 2]
```diff
@@ -549,65 +534,77 @@ func computePlanetStarbaseSpec(rules *Rules, player *Player, planet *Planet) Pla
...
+//
+// This is called by the main ComputePlanetSpec function as well as anytime a player
+// changes research contribution amounts
 func (spec *PlanetSpec) computeResourcesPerYearAvailable(player *Player, planet *Planet) {
 	if planet.ContributesOnlyLeftoverToResearch {
 		spec.ResourcesPerYearAvailable = spec.ResourcesPerYear
 		spec.ResourcesPerYearResearch = 0
 	} else {
-		spec.ResourcesPerYearResearch = int(float64(spec.ResourcesPerYear) * float64(player.ResearchAmount) / 100.0)
+		spec.ResourcesPerYearResearch = int(float64(spec.ResourcesPerYear*player.ResearchAmount) / 100)
```
Comment (sirgwain) [inline cs/planet.go]: I'm not sure we need to cast this as a float at all.

Comment (Bertie690) [reply cs/planet.go]: oh good catch - it's being floored anyways so we can just use ints instead

File: cs/planet.go (hunk 1 above)
Comment (Bertie690) [reply cs/planet.go]: The fancy rounding is just the roundTo100 function - I have some local changes that refactor it to take a function argument to decide how exactly to round (ceil, floor, etc.), so this is just a reminder to refactor it later once I push those.

**Review by sirgwain — DISMISSED** [review]

File: cmd/generate.go [hunk 3]
```diff
@@ -42,6 +43,27 @@ func newGenerateTechsJson() *cobra.Command {
...
+			rules := cs.NewRules()
+
+			rulesJson, err := json.MarshalIndent(rules, "", "  ")
+			if err != nil {
+				return fmt.Errorf("failed to marshal rules to json")
+			}
+
+			fmt.Println(string(rulesJson))
+			return nil
+		},
```
Comment (Bertie690) [inline cmd/generate.go:61]: You know, we could just have these write to the files themselves rather than printing stdout for the caller process to capture...

**Review by sirgwain — DISMISSED** [review]

File: magefiles/utils.go [hunk 4]
```diff
@@ -87,7 +87,7 @@ func Images() error {
 	if err != nil {
 		return mg.Fatalf(1, "error during io.Copy: \n%w", err)
 	}
-	tmpFile.Close()
+	tmpFile.Close() // close temp file since we don't need it anymore
```
Comment (sirgwain) [inline magefiles/utils.go]: Can this be in a defer?

Comment (sirgwain) [reply magefiles/utils.go]: Oh maybe not. We need to read it right away

**Review by sirgwain — DISMISSED** [review]

File: magefiles/utils.go (hunk 4 above)
Comment (Bertie690) [reply magefiles/utils.go]: We don't need the actual temp file open anytime later in the function so I'd rather close it immediately.
We use a ZipReader to open the zip file immediately afterwards.

Comment (sirgwain) [reply magefiles/utils.go]: You use defer to make sure the file gets closed in case of an error in the function, but in this case we need it closed mid function. I see two ways to solve this.

1. split into two functions, one to create and fill the temp file (with a defer to close), and one to unzip the temp file after it's been created.
2. set the tmp file to nil when closing and check that in the defer

```go
	defer func() {
		if tmpFile != nil {
			tmpFile.Close()
			os.Remove(tmpFile.Name())
		}
	}()
```

Comment (Bertie690) [reply magefiles/utils.go]: Honestly I don't really care when it gets closed, but splitting it into 2 files is probably a good idea regardless.

**Review by sirgwain — APPROVED** [review]
