### PR TITLE
MT part tech trading + scrapping fixes

### LINKED ISSUE #414: Wrong minerals from colonizing
Colonizing gives more minerals back seems it is the same as scrapping atr the moment it seems.

### PR DESCRIPTION
**Pull request by Bertie690**
TODO:
- [x] Move code to its own function because both scenarions (scrapping/battle) use nearly the exact same code (i quite literally copypasted the entire thing and hit F2 a couple times)
- [x] Add tests for MT part trading 
- [x] Add messages for it to frontend bc I forgot

Fixes #414, #205, #470

### CODE REVIEW

File: cs/message.go [hunk 1]
```diff
@@ -171,6 +171,8 @@ const (
 	PlayerMessagePlayerTechLevelGainedInvasion
 	PlayerMessagePlayerTechLevelGainedScrapFleet
 	PlayerMessagePlayerTechLevelGainedBattle
+	PlayerMessagePlayerMysteryTechGainedScrapFleet
+	PlayerMessagePlayerMysteryTechGainedBattle
```
Comment (sirgwain) [inline cs/message.go]: unfortunately, these have to be added at the end because they are incremented numbers. If you add them in the middle, all existing games will have messageIds that are incorrect.

At some point I'll convert these message types to strings so I can sort them, but that would involve a relatively complicated database upgrade step (because they're ints in the database as well...)

File: cs/player.go [hunk 2]
```diff
@@ -42,6 +42,7 @@ type Player struct {
 	Spec                      PlayerSpec           `json:"spec,omitempty"`
 	leftoverResources         int
 	techLevelGained           bool
+	mtPartGained              bool
```
Comment (sirgwain) [inline cs/player.go]: please make it more generic for future mods. `acquirablePartGained`

Comment (Bertie690) [reply cs/player.go]: What should the names of the messages be?
Should it be `TechPartGained`, `TechComponentGained`, `AcquirableTechGained` or something else entirely?

Comment (sirgwain) [reply cs/player.go]: `PlayerMessagePlayerTechPartGained`

Comment (Bertie690) [reply cs/player.go]: Wil do find and replace when i have time on computer

File: cs/message.go (hunk 1 above)
Comment (Bertie690) [reply cs/message.go]: Moved em to the end.

**Review by sirgwain — APPROVED** [review]
