### PR TITLE
Partial Population fixes

### LINKED ISSUE #578: Add partial population growth/death tracking
Basically just need to add a tracker for fractions of a pop on a planet for pop growth purposes. Nothing else cares about fractional colonists anyways.

### LINKED ISSUE #632: Inaccurate starting minconc/surface mineral starting bonuses
The starting bonuses don't match.

### LINKED ISSUE #643: AR resource calculation does not use min hab
AR planets with negative hab do generate negative resources. 

Calculation of resources should use a minimum hab of 25% in case hab is lower than that.

### PR DESCRIPTION
**Pull request by Bertie690**
Also fixes starting minconcs because I could

### CODE REVIEW

File: cs/bomb.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ import (
 type Bomb struct {
 	Quantity             int     `json:"quantity,omitempty"`
 	KillRate             float64 `json:"killRate,omitempty"`
-	MinKillRate          int     `json:"minKillRate,omitempty"`
+	MinKillRate          int     `json:"minKillRate,omitempty"` //? Why is MinKillRate an int but KillRate a float?
```
Comment (sirgwain) [inline cs/bomb.go]: Because one is a percent and another is number of colonists per bomb.

File: cs/planet.go [hunk 2]
```diff
@@ -237,13 +286,14 @@ func (p *Planet) emptyPlanet() {
 	// clear any production or other orders from the previous owner
 	p.Defenses = 0
 	p.PlanetOrders = PlanetOrders{}
-	p.setPopulation(0)
+	p.Cargo.Colonists = 0 // doesn't reset partial pop to be consistent with base game
```
Comment (sirgwain) [inline cs/planet.go]: We can fix this to reset partial pop unless there is some strategic element I'm not aware of.

File: cs/intel.go [hunk 3]
```diff
@@ -318,12 +323,15 @@ func (d *discover) discoverPlanet(rules *Rules, planet *Planet, penScanned bool)
 		}
 
 		// players & their allies know their exact planet pops, but foreign pop readings are slightly off
-		sharingMapWithOwner := player.IsSharingMap(planet.PlayerNum)
-		if ownedByPlayer || sharingMapWithOwner {
-			intel.Spec.Population = planet.population()
+		// @sirgwain: Should this be "you are friend of the planet player" or "they are friends with you"?
+		// Seems kinda off that you can get better intel just by swapping to friend on your end
+		if ownedByPlayer || player.IsFriend(planet.PlayerNum) ||
```
Comment (sirgwain) [inline cs/intel.go]: yes, it should be the other way around. Also, isSharingMap already checks for friend, so we don't need both checks here. You can't share a map and not be a friend (or rather, sharing a map without being friends does nothing)

File: cs/message.go [hunk 4]
```diff
@@ -698,7 +700,10 @@ func (m *messageClient) planetBuiltStarbase(player *Player, planet *Planet, flee
 
 func (m *messageClient) planetColonized(player *Player, planet *Planet) {
 	text := fmt.Sprintf("Your colonists are now in control of %s.", planet.Name)
```
Comment (sirgwain) [inline cs/message.go]: as long as the `text` field is set, the UI will not render messages and will just default to whatever `text` is set to. I've been removing the text setting as I've migrated messages to the `*MessageDetail.svelte` files.

File: cs/mineralpacket.go [hunk 5]
```diff
@@ -210,175 +210,185 @@ func (packet *MineralPacket) getDamage(planet *Planet, planetPlayer *Player) Min
...
+			result := terraformer.PermaformOneStep(planet, player, habType)
+			direction += result.Direction
+			if !result.Terraformed() {
+				// BaseHab already perfect for this hab type; move on
+				break
 			}
 		}
+
+		// tell player about the terraforming for this type
+		if direction != 0 {
```
Comment (sirgwain) [inline cs/mineralpacket.go:388]: what happens if we perform twice, once in one direction and once in another? Wouldn't this be 0?

Comment (Bertie690) [reply cs/mineralpacket.go:388]: Yes - but that should never happen since we check each hab type one by one, always terraform the _best_ result and break as soon as it's perfect.

File: cs/planet.go (hunk 2 above)
Comment (Bertie690) [reply cs/planet.go:289]: I dunno - I suppose it would depend on whether you classify it as a bug or a feature.

File: cs/message.go (hunk 4 above)
Comment (Bertie690) [reply cs/message.go:702]: Yup - that's why I put em in the UI.

File: cs/mineralpacket.go (hunk 5 above)
Comment (sirgwain) [reply cs/mineralpacket.go:388]: No I mean what if they need -grav and +rad?

Comment (Bertie690) [reply cs/mineralpacket.go:388]: Then we message twice. 
This is still inside the hab type loop

File: cs/message.go (hunk 4 above)
Comment (Bertie690) [reply cs/message.go]: Okee- I reverted the changes to message.go

File: cs/intel.go (hunk 3 above)
Comment (Bertie690) [reply cs/intel.go:328]: this is an OR check but yeah

File: frontend/src/lib/andCommandList.ts [hunk 6]
```diff
@@ -20,15 +19,14 @@ export function andCommaList(items: string[], emptyResult = ''): string {
 		return `${filteredItems[0]} and ${filteredItems[1]}`;
 	}
 
-	for (let i = 0; i < filteredItems.length; i++) {
+	return filteredItems.reduce((prevVal, currVal: string, i: number) => {
```
Comment (sirgwain) [inline frontend/src/lib/andCommandList.ts]: I know JavaScript is all about functional programming but in general there is nothing wrong with a for loop. No need to replace it with reduce.

**Review by sirgwain — DISMISSED** [review]

File: frontend/src/lib/andCommandList.ts (hunk 6 above)
Comment (Bertie690) [reply frontend/src/lib/andCommandList.ts]: Np - I'll revert it then.

File: frontend/src/lib/types/Planet.ts [hunk 7]
```diff
@@ -122,159 +114,28 @@ export class CommandedPlanet implements Planet {
 		hasStargate: false
 	};
 
-	// get the population from a planet's cargo
-	public get population() {
+	public get population(): number {
+		console.log(this.cargo.colonists);
```
Comment (sirgwain) [inline frontend/src/lib/types/Planet.ts]: This looks like it was left in accidentally.

**Review by sirgwain — CHANGES_REQUESTED** [review]

File: frontend/src/lib/types/Planet.ts (hunk 7 above)
Comment (Bertie690) [reply frontend/src/lib/types/Planet.ts]: 😅

**Review by sirgwain — APPROVED** [review]
